# Generated by Django 3.2.6 on 2021-09-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0002_auto_20210909_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
