# Generated by Django 3.2.6 on 2021-09-09 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0003_jobs_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='servicio_tecnico.categoria'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
    ]
